import { Router } from "express";
import verifyJWT from "../middlewares/auth.middleware.js";
import { upload } from "../middlewares/multer.middleware.js";
import { toggleVideoLike,toggleCommentLike,toggleTweetLike,getLikedVideos } from "../controllers/likes.controller.js";
const router = Router();
router.route("/togglevideolike/:videoId").post(verifyJWT,toggleVideoLike);
router.route("/togglecommentlike/:commentId").post(verifyJWT,toggleCommentLike);
router.route("/toggletweetlike/:tweetId").post(verifyJWT,toggleTweetLike);
router.route("/getlikedvideos").get(verifyJWT,getLikedVideos);
export default router; 